/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GithubIcon: typeof import('./src/components/svg-icons/GithubIcon.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LinkedinIcon: typeof import('./src/components/svg-icons/LinkedinIcon.vue')['default']
    MainPage: typeof import('./src/components/MainPage.vue')['default']
    StackOverflowIcon: typeof import('./src/components/svg-icons/StackOverflowIcon.vue')['default']
  }
}
